app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/',['as' => 'programacao.index', 'uses' => 'ProgramacoesController@index']);
Route::get('/programacao', ['as' => 'programacao.listagem', 'uses' => 'ProgramacoesController@listagem']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function (){

    Route::resource('/user', 'UsersController', ['except' => ['destroy', 'create', 'store', 'show']]);

    Route::group(['prefix' => 'programacao', 'as' => 'programacao.'], function (){
        Route::get('/', ['as' => 'listagemAdmin', 'uses' => 'ProgramacoesController@listagemAdmin']);
        Route::get('/add', ['as' => 'add', 'uses' => 'ProgramacoesController@create']);
        Route::get('/edit/{id}', ['as' => 'edit', 'uses' => 'ProgramacoesController@edit']);
        Route::post('/store', ['as' => 'store', 'uses' => 'ProgramacoesController@store']);
        Route::post('/update/{id}', ['as' => 'update', 'uses' => 'ProgramacoesController@update']);
        Route::get('/destroy/{id}', ['as' => 'destroy', 'uses' => 'ProgramacoesController@destroy']);
    });

    Route::group(['prefix' => 'config', 'as' => 'config.'], function (){
        Route::get('/', ['as' => 'index', 'uses' => 'ConfigController@index']);
        Route::get('/add', ['as' => 'add', 'uses' => 'ConfigController@create']);
        Route::get('/edit/{id}', ['as' => 'edit', 'uses' => 'ConfigController@edit']);
        Route::post('/store', ['as' => 'store', 'uses' => 'ConfigController@store']);
        Route::post('/update/{id}', ['as' => 'update', 'uses' => 'ConfigController@update']);
    });

    Route::get('/', ['as' => 'admin.index', 'uses' => 'ProgramacoesController@listagemAdmin']);
});

Route::auth();

app/Config.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Config extends Model
{
    protected $casts = [
        'status' => 'boolean',
    ];

    protected $fillable = [
        'status',
        'aviso',
        'iframe',
    ];

    /*public function setStatusAttribute($value)
    {
        //echo $value;
        if($value < 0){
            $this->attributes['status'] = false;
        }else{
            $this->attributes['status'] = true;
        }

    }

    public function getStatusAttribute($value)
    {
        //echo $value;
        /*if(empty($value)){
            $this->attributes['status'] = false;
        }
        $this->attributes['status'] = true;
    }*/
}

app/Programacao.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Programacao extends Model
{
    protected $table = "programacoes";

    protected $casts = [];

    protected $fillable = [
        'titulo',
        'data',
        'horario',
        'celebrante',
        'canticos',
        'noiteiros',
        'observacao',
        'orientacoes',
    ];

    /*public function getDataAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->format('d/m/Y');
    }*/
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/ConfigController.php
<?php

namespace App\Http\Controllers;

use App\Config;
use Illuminate\Http\Request;

use App\Http\Requests;

class ConfigController extends Controller
{
    public function index()
    {
        $config = Config::first();
        return view('admin.config.index', compact('config'));
    }

    public function create()
    {
        return view('admin.config.create');
    }

    public function store(Request $request)
    {
        //dd($request->all());
        Config::create($request->all());
        return redirect()->route('config.index');
    }

    public function edit($id)
    {
        $config = Config::findOrFail($id);
        return view('admin.config.edit', compact('config'));
    }

    public function update(Request $request, $id)
    {
        $status = $request->input('status');
        $aviso = $request->input('aviso');
        $iframe = $request->input('iframe');

        if (empty($status)) {
            $status = false;
        } else {
            $status = true;
        }
        $config = Config::findOrFail($id);
        $config->fill(['status' => $status, 'aviso' => $aviso, 'iframe' => $iframe])->save();
        return redirect()->route('config.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProgramacoesController.php
<?php

namespace App\Http\Controllers;

use App\Config;
use App\Programacao;
use Illuminate\Http\Request;
use App\Http\Requests;

class ProgramacoesController extends Controller
{
    public function index()
    {
        $config = Config::first();
        $dados = Programacao::where('data', '=', date('Y-m-d'))->first();
        if(empty($config) || empty($dados)){
            return redirect()->route('programacao.listagem');
        }
        return view('welcome', compact('dados', 'config'));
    }

    public function listagem()
    {
        $dados = Programacao::orderBy('data', 'asc')->get();
        return view('programacao.index', compact('dados'));
    }

    public function listagemAdmin()
    {
        $dados = Programacao::orderBy('data', 'asc')->get();
        return view('admin.programacao.index', compact('dados'));
    }

    public function create()
    {
        return view('admin.programacao.create');
    }

    public function store(Request $request)
    {
        Programacao::create($request->all());
        return redirect()->route('programacao.listagemAdmin');
    }

    public function edit($id)
    {
        $dados = Programacao::findOrFail($id);
        return view('admin.programacao.edit', compact('dados'));
    }

    public function update(Request $request, $id)
    {
        $programacao = Programacao::findOrFail($id);
        $programacao->fill($request->all())->save();
        return redirect()->route('programacao.listagemAdmin');
    }

    public function destroy($id)
    {
        Programacao::destroy($id);
        return redirect()->route('programacao.listagemAdmin');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dados = User::findOrFail($id);
        return view('admin.user.edit', compact('dados'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $dados = ['name' => $request->input('name'), 'email' => $request->input('email')];
        if (!empty($request->input('password'))) {
            $dados = array_merge($dados, ['password' => $request->input('password')]);
        }
        $user->fill($dados)->save();
        return redirect()->route('admin.user.index');
    }
}

resources/views/admin/config/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="page-header">
                    <h1>Adicionar Configuração</h1>
                </div>
                {!! Form::open(['method' => 'post', 'route' => 'config.store']) !!}

                <div class="checkbox">
                    <label>
                        {{ Form::checkbox('status', '1', true) }} Status
                    </label>
                </div>

                <div class="form-group">
                    {{ Form::label('aviso', 'Aviso', ['class' => 'awesome']) }}
                    {{ Form::text('aviso', null, ['class' => 'form-control']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('iframe', 'Iframe', ['class' => 'awesome']) }}
                    {{ Form::textarea('iframe', null, ['class' => 'form-control']) }}
                </div>

                {{ Form::submit('Salvar', ['class' => 'btn btn-primary']) }}

                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/config/edit.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Editando Configurações
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Configurações
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')

    {!! Form::model($config, ['method' => 'post', 'route' => ['config.update', $config]]) !!}

    <div class="checkbox">
        <label>
            {{ Form::checkbox('status', '1', $config->status) }} Status
        </label>
    </div>

    <div class="form-group">
        {{ Form::label('aviso', 'Aviso', ['class' => 'awesome']) }}
        {{ Form::text('aviso', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('iframe', 'Iframe', ['class' => 'awesome']) }}
        {{ Form::textarea('iframe', null, ['class' => 'form-control']) }}
    </div>

    {{ Form::submit('Salvar', ['class' => 'btn btn-primary']) }}

    {!! Form::close() !!}

@endsection

resources/views/admin/config/index.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Configurações
                <small>- @if(!empty($config))<a href="{{ route('config.edit', ['id' => $config->id]) }}">Editar</a>
                    -@endif
                    <a href="{{ route('config.add') }}">Adicionar</a></small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Configurações
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')
    @if(!empty($config))
        <div class="col-md-4">
            <p><b>Status: </b> @if($config->status) <span class="label label-success">Ativado</span> @else <span class="label label-danger">Desativado</span> @endif</p>
            <p><b>Aviso: </b>{{$config->aviso}}</p>
        </div>
        <div class="col-md-8">
            <div class="embed-responsive embed-responsive-16by9">
                {!! $config->iframe !!}
            </div>
            <hr>
            <a href="http://http://stmv2.srvstm.com/walberjefferson/walberjefferson/playlist.m3u8"><img src="http://playerv.srvstm.com/img/icones/img-icone-player-android.png" width="32" height="32" /></a>
            <a href="http://stmv2.srvstm.com/walberjefferson/walberjefferson/playlist.m3u8"><img src="http://playerv.srvstm.com/img/icones/img-icone-player-blackberry.png" width="32" height="32" /></a>
            <a href="http://stmv2.srvstm.com/walberjefferson/walberjefferson/playlist.m3u8"><img src="http://playerv.srvstm.com/img/icones/img-icone-player-iphone.png" width="32" height="32" /></a>
        </div>
    @endif
@endsection

resources/views/admin/programacao/create.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Adicionar <small> Programação</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Adicionar
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')
    {!! Form::open(['method' => 'post', 'route' => 'programacao.store']) !!}

    <div class="form-group">
        {{ Form::label('titulo', 'Titulo', ['class' => 'awesome']) }}
        {{ Form::text('titulo', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('data', 'Data', ['class' => 'awesome']) }}
        {{ Form::date('data', \Carbon\Carbon::now(), ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('horario', 'Horário', ['class' => 'awesome']) }}
        {{ Form::text('horario', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('celebrante', 'Celebrante', ['class' => 'awesome']) }}
        {{ Form::text('celebrante', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('canticos', 'Cânticos', ['class' => 'awesome']) }}
        {{ Form::text('canticos', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('noiteiros', 'Noiteiros', ['class' => 'awesome']) }}
        {{ Form::textarea('noiteiros', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('observacao', 'Observação', ['class' => 'awesome']) }}
        {{ Form::text('observacao', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('orientacoes', 'Orientações Ultimo dia', ['class' => 'awesome']) }}
        {{ Form::textarea('orientacoes', null, ['class' => 'form-control ckeditor']) }}
    </div>

    {{ Form::submit('Salvar', ['class' => 'btn btn-primary']) }}

    {!! Form::close() !!}
@endsection

resources/views/admin/programacao/edit.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Editando <small> - {{ $dados->titulo }}</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Editar
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')
    {!! Form::model($dados, ['method' => 'post', 'route' => ['programacao.update', $dados]]) !!}

    <div class="form-group">
        {{ Form::label('titulo', 'Titulo', ['class' => 'awesome']) }}
        {{ Form::text('titulo', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('data', 'Data', ['class' => 'awesome']) }}
        {{ Form::date('data', (empty($dados->data))? \Carbon\Carbon::now() : $dados->data, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('horario', 'Horário', ['class' => 'awesome']) }}
        {{ Form::text('horario', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('celebrante', 'Celebrante', ['class' => 'awesome']) }}
        {{ Form::text('celebrante', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('canticos', 'Cânticos', ['class' => 'awesome']) }}
        {{ Form::text('canticos', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('noiteiros', 'Noiteiros', ['class' => 'awesome']) }}
        {{ Form::textarea('noiteiros', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('observacao', 'Observação', ['class' => 'awesome']) }}
        {{ Form::text('observacao', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('orientacoes', 'Orientações Ultimo dia', ['class' => 'awesome']) }}
        {{ Form::textarea('orientacoes', null, ['class' => 'form-control ckeditor']) }}
    </div>

    {{ Form::submit('Salvar', ['class' => 'btn btn-primary']) }}

    {!! Form::close() !!}

@endsection

resources/views/admin/programacao/index.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Listagem <small>Completa</small>
                <small class="pull-right" style="position: relative; top: 15px;">{{ count($dados) }} Resultados</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Listagem
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Titulo</th>
            <th>Celebrante</th>
            <th width="8%">Data</th>
            <th width="5%">Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($dados as $d)
            <tr>
                <td>{{$d->titulo}}</td>
                <td>{{$d->celebrante}}</td>
                <td class="text-center">{{\Carbon\Carbon::parse($d->data)->format('d/m/Y')}}</td>
                <td class="text-center">
                    <a href="{{route('programacao.edit', ['id' => $d->id])}}" class="text-success"><i class="fa fa-pencil" aria-hidden="true"></i></a> |
                    <a href="{{route('programacao.destroy', ['id' => $d->id])}}" class="text-danger" onclick="javascript:if(!confirm('Deseja realmente excluir {{$d->titulo}}?'))return false;"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Editando <small>{{ $dados->name }}</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Usuários
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')
    {!! Form::model($dados, ['method' => 'put', 'route' => ['admin.user.update', $dados]]) !!}

    <div class="form-group">
        {{ Form::label('name', 'Nome', ['class' => 'awesome']) }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'E-mail', ['class' => 'awesome']) }}
        {{ Form::text('email', null, ['class' => 'form-control']) }}
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Senha', ['class' => 'awesome']) }}
        {{ Form::password('password', ['class' => 'form-control']) }}
    </div>

    {{ Form::submit('Salvar', ['class' => 'btn btn-primary']) }}

    {!! Form::close() !!}

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('title_header')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Usuários <small>Cadastrados</small>
            </h1>
            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i> <a href="{{route('admin.index')}}">Dashboard</a> / Usuários
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
@endsection

@section('content')
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th width="5%" nowrap>Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td class="text-center">
                    <a href="{{route('admin.user.edit', ['id' => $user->id])}}" class="text-success"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Festa de São Cristóvão</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/css/plugins/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}
</head>
<body>

<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('admin.index') }}">Painel de Administração</a>
        </div>

        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">
            <li class="dropdown">
                @if (Auth::guest())
                    <a href="{{ url('/login') }}">Login</a>
                @else
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-user"></i> {{ Auth::user()->name }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{{ route('admin.user.index') }}"><i class="fa fa-fw fa-user"></i> Perfil</a>
                        </li>
                        <li>
                            <a href="{{ route('config.index') }}"><i class="fa fa-btn fa-gear"></i> Configurações</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i> Sair</a></li>
                    </ul>
                @endif
            </li>
        </ul>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li class="active">
                    <a href="{{ route('admin.index') }}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                </li>
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#listagem"><i
                                class="fa fa-fw fa-arrows-v"></i> Listagem <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="listagem" class="collapse">
                        <li>
                            <a href="{{route('programacao.add')}}">Adicionar novo</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            @yield('title_header')

            @yield('content')

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- /#page-wrapper -->
</div>

<!-- JavaScripts -->
<!-- jQuery -->
<script src="/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/js/bootstrap.min.js"></script>

<!-- Morris Charts JavaScript -->
<script src="/js/plugins/morris/raphael.min.js"></script>
<script src="/js/plugins/morris/morris.min.js"></script>
<script src="/js/plugins/morris/morris-data.js"></script>
<script src="/js/ckeditor/ckeditor.js"></script>


{{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/programacao/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <div class="row hidden-xs">
                        <div class="col-md-2">
                            <h4 style="position: relative; top: 30px;">
                                <a href="{{route('programacao.index')}}" class="hidden-xs">Voltar</a>
                            </h4>
                        </div>
                        <div class="col-md-8">
                            <h1 class="text-center">Programação Festa de São Cristóvão</h1>
                        </div>
                    </div>
                    <h1 class="text-center hidden-md hidden-lg">Programação Festa de São Cristóvão</h1>
                </div>
                </div>
            <div class="col-md-12">
                <dl class="dl-horizontal">
                    @foreach($dados as $d)
                        @if($d->titulo)<h2 class="text-primary">{{$d->titulo}}</h2>@endif
                        @if($d->data)<h4>Data: <small>{{\Carbon\Carbon::parse($d->data)->format('d/m/Y')}}</small></h4>@endif
                        @if($d->horario)<h4>Horário: <small>{{$d->horario}}</small></h4>@endif
                        @if($d->celebrante)<h4>Presidente: <small>{{$d->celebrante}}</small></h4>@endif
                        @if($d->canticos)<h4>Encarregado dos cânticos: <small>{{$d->canticos}}</small></h4>@endif
                        @if($d->noiteiros)<h4>Noiteiros: <small>{!! $d->noiteiros !!}</small></h4>@endif
                        @if($d->observacao)<h4>Observação: <small>{{$d->observacao}}</small></h4>@endif
                        @if($d->orientacoes)
                            <hr>
                            {!! $d->orientacoes !!}
                        @endif
                        <hr>
                    @endforeach
                </dl>
            </div>
        </div>
    </div>
@endsection